---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /calc(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: calculator
                port:
                  number: 5002

# https://kubernetes.github.io/ingress-nginx/examples/rewrite/
# https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  strategy: {}
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - image: ugwuanyi/apps-calc
          name: calc
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculator
  name: calculator
spec:
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
  selector:
    app: calculator
  type: ClusterIP
